### ISSUE TITLE
Help with training on segmenter.py

### ISSUE THREAD

**Issue by js-kki** [Hierakonpolis/MU-Net-R#1]
Hello, I have run into trouble when attempting to use segmenter.py. I have axial volumes, (25x128x128), and attempted to use the pre-trained models in MU-Net-R to run segmenter.py on these scans. The outputs, when loaded in, contained zeroes except for ones at the bound indices. When attempting to add the --train flag, I wasn't sure how to incorporate all of my .nii files to train the model on, or if there were any validation samples around, and am unsure whether I need to modify anything regarding the folds/foldfiles. I feel as though I'm doing something wrong on the command line, but I'm unsure how to proceed. Any tips would be fantastic! I created a private repo with two axial .nii datasets if necessary.

**Comment by Hierakonpolis** [comment]
Could you please paste the command you are using and the directory tree of your dataset (e.g. `tree` command in bash) I would need a bit more information to understand what is missing for you to train the network.

**Comment by js-kki** [comment]
Here are the scans that I was using: https://github.com/js-kki/KKI-MUNet/tree/main/scans

Here is the output of an attempt of running segmenter.py on one of the trained models: https://github.com/js-kki/KKI-MUNet/tree/main/segmentation_attempt1

Here are a few train commands I have tried to submit:
python3 segmenter.py --savefolder ./trained_models/ --train ./ multislice_image.nii test_1

python3 segmenter.py --savefolder ./trained_models/ --train --mask multislice_image_Mask.nii.gz, multislice_imageRE0972 --folds 2 ./ multislice_imageWM9986.nii EBmodVal_0

python3 segmenter.py --savefolder ./trained_models/ --train --mask multislice_image_Mask.nii.gz --folds 2 ./ multislice_imageWM9986.nii, multislice_imageRE0972 test_1

**Comment by Hierakonpolis** [comment]
So, files should be organized in different folders, so inside your root folder you would have something like:
```
dataset_root
--1
----scan.nii
----label1.nii.gz
----label2.nii.gz
----brain_mask.nii.gz
--2
----scan.nii
----label1.nii.gz
----label2.nii.gz
----brain_mask.nii.gz
```

Then you would train it with something like:

python3 segmenter.py /path/to/dataset_root scan.nii my_model --train --savefolder /path/to/my_trained_models --mask brain_mask.nii.gz --labels label1.nii.gz label2.nii.gz

If you are still experiencing issues please copy and paste any error messages you might be receiving and the actual folder structure in which your data is organized.

**Comment by js-kki** [comment]
> So, files should be organized in different folders, so inside your root folder you would have something like:
> 
> ```
> dataset_root
> --1
> ----scan.nii
> ----label1.nii.gz
> ----label2.nii.gz
> ----brain_mask.nii.gz
> --2
> ----scan.nii
> ----label1.nii.gz
> ----label2.nii.gz
> ----brain_mask.nii.gz
> ```
> 
> Then you would train it with something like:
> 
> python3 segmenter.py /path/to/dataset_root scan.nii my_model --train --savefolder /path/to/my_trained_models --mask brain_mask.nii.gz --labels label1.nii.gz label2.nii.gz

All I have is the scans, no mask or labels. The attempt of running segmenter without these is in the folder titled "segmentation_attempt1", and the output mask is unusable. Is it possible to run this without the mask/labels, or is it possible to extrapolate the mask and labels from your trained runs?

**Comment by Hierakonpolis** [comment]
Well, this is a supervised learning algorithm and you would need to retrain if for your dataset, so I'm afraid that without some labeled data this won't work. I do not have a set of weights for a model general enough to work on any given MRI dataset.

Something you could consider doing is to prepare manual labels for a small number of samples, e.g. 5, use that to label a larger dataset, refine manually, and repeat on more data. Whether this is worth it depends on your use case.

**Comment by js-kki** [comment]
Thank you for the advice, I'll be sure to get back to you if I have further questions.

**Comment by js-kki** [comment]
I now have some trained models of my own- would you potentially have any free time to show me how to set up the segmenter.py script call?

**Comment by Hierakonpolis** [comment]
We could, but could you please first tell me what did you try, and which problem you ended up facing when you tried using segmenter.py?

**Comment by js-kki** [comment]
Apologies for the late reply- I'm working off of an RDC so I can't copy/paste attempts. Instead, I'll write generally what I've been attempting to input. For background, I have .tar file models, .nii brain scans, .nii masks and .nii labels. I've attempted using the three hardcoded inputs and savefolder just to get a preliminary run started. However, even with the correct path inputs, I'm running into an error where the program can't find my model. I'm probably misinterpreting the inputs or just not being rigorous enough.

**Comment by Hierakonpolis** [comment]
Well, having the output of `$ tree` and the command you are using would be quite hepful understanding what's going on. Perhaps you could try a screenshot, or finding a way to turn the clipboard on with your remote desktop. Or paste in a file and send it to yourself.

**Comment by js-kki** [comment]
I'll give that a go

**Comment by js-kki** [comment]
apologies for formatting:

```
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m 3mo_s1 --savefolder ./ 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1 in .
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m 3mo_s1 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1 in /data/home/yadav_lab_2/Documents/KKI-MUNet
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m 3mo_s1 --savefolder ./notebooks/
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1 in notebooks
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m.nii 3mo_s1.tar --savefolder ./notebooks/ 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1.tar in notebooks
```
<img width="858" height="464" alt="Image" src="https://github.com/user-attachments/assets/001a2b5d-29b9-4aed-b8ed-a0a3cd2efd0d" />

<img width="848" height="429" alt="Image" src="https://github.com/user-attachments/assets/13d8aee8-7004-478c-bf22-4887dc958333" />

**Comment by Hierakonpolis** [comment]
So, from your screenshot, it would seem the models might be located in 
`/data/home/yadav_lab_2/Documents/KKI-MUNet/notebooks`
It seems to me you tried these paths:
`notebooks`
`/data/home/yadav_lab_2/Documents/KKI-MUNet`
`.`

I can see a couple of problems here. One is that it might make more sense to just use the absolute path:
`/data/home/yadav_lab_2/Documents/KKI-MUNet/notebooks`
The other is that I am not sure whether this is indeed the directory in which you saved your models. Ideally, when training the model, you would have specified a directory where to save the models, like this:
`... --savefolder /path/to/models/directory`
You should just point once again to the same location.

It would also be best if this directory was only used for the models, and not for other things too. It might actually just work anyway, but I must admit back then it never occurred to me that one might just want mix other things in the same path.

**Comment by js-kki** [comment]
I put the models in a new folder, but I'm running into similar issues-

```
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m.nii 3mo_s1.tar --savefolder /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models/ 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1.tar in /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m.nii 3mo_s1 --savefolder /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models/ 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1 in /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m.nii 3mo_s1 --savefolder /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1 in /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models
(pt-gpu) yadav_lab_2@ASH-FMK-MRI-01:/data/home/yadav_lab_2/Documents/KKI-MUNet$ python3 segmenter.py ./brain_structural_masks_segmentation/nii/Template3/s1 PBS_4_RR_m.nii 3mo_s1 --savefolder /home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models 
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/data/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `[torchvision.io](http://torchvision.io/)`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yadav_lab_2/anaconda3/envs/pt-gpu/lib/python3.11/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /opt/conda/envs/bld/conda-bld/pytorch-select_1719512383855/work/torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
Inference
Traceback (most recent call last):
  File "/data/home/yadav_lab_2/Documents/KKI-MUNet/segmenter.py", line 209, in <module>
    raise NameError('No models found for inference named '+str(args.modelname)+' in '+str(args.savefolder))
NameError: No models found for inference named 3mo_s1 in /home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models
```

**Comment by Hierakonpolis** [comment]
It might help to also paste the content of that folder
`ls /data/home/yadav_lab_2/Documents/KKI-MUNet/brain_structural_masks_segmentation/tar_models `

**Comment by Hierakonpolis** [comment]
It should be looking for model files according to this pattern:
`modelname+'_[0-9]*.pth'`
Which I expect would be matched to the pattern generated when training models using the same name as an argument

**Comment by js-kki** [comment]
<img width="1166" height="614" alt="Image" src="https://github.com/user-attachments/assets/8373fa3b-d104-4c7a-bae6-a3824cdf7439" />
I made all of my models using the MU-Net notebook

**Comment by Hierakonpolis** [comment]
I see. These models will not work. The segmenter script is used both for training, by using the --train option, and for inference. This is described in readme.md, and in case that might be hard to find I will paste it again here. Only models created in this way are supported. If you prefer to customize the models in your own way, you will also have to write your inference code.

## Training
To use this script the data is assumed to be organized in a series of folders, one for each sample, sharing the same root folder. Each folder needs to contain a file for the MRI scan and one for each ROI you want segmented, as a binary mask in the same space as the MRI. Files need to have the same name in each folder. Do not forget to set the `--train` option for training. Defaults are as set in our paper, check the usage section below for how to change them if needed. The number of blocks on the encoder and decoder branches can simply be changed by changing the lenght of the `--kernels` option: 8 16 32 64 64 64 64 mean you will train a network with 7 blocks on each branch, 16 32 means there will only be two blocks.

**Comment by js-kki** [comment]
I want to make sure I'm nesting the directories correctly:
I am training 4 separate slices, labeled accordingly, starting with s1. I tried a couple variations of nesting as I'm a bit confused as to how I'm supposed to have directories labeled and ordered.


The first thing I tried had at the root directory: 4 Labels folders, 4 Masks folders and 4 Volumes folders. In each of those folders, there were sub-folders for each slice (s1-s4), and within the slice folders were the .nii files. Everything within s1 corresponded between all of the Labels, Masks, and Volumes folders. This was probably too divided and convoluted.


The second thing I tried was to reorganize the directories, such that I made s1 a root directory. Contained within s1 were 4 labels folders, 4 mask folders and 4 volume folders. Within each of those folders were .nii files that have matching names. This one didn't work either. I'm not too sure how to organize everything in a manner that it'll get read:

<img width="1138" height="650" alt="Image" src="https://github.com/user-attachments/assets/5110baf1-c96c-43ce-a830-737d4b2f44d0" />

<img width="1127" height="647" alt="Image" src="https://github.com/user-attachments/assets/659bd78c-1707-42d9-acf3-2e695a21bec6" />

**Comment by Hierakonpolis** [comment]
> To use this script the data is assumed to be organized in a series of folders, one for each sample, sharing the same root folder. Each folder needs to contain a file for the MRI scan and one for each ROI you want segmented, as a binary mask in the same space as the MRI

This mean it's assuming you have a folder for each sample with content like this:
subj1:
-  scan_file.nii.gz
-  roi1.nii.gz
-  roi2.nii.gz

subj2:
-  scan_file.nii.gz
-  roi1.nii.gz
-  roi2.nii.gz

**Comment by js-kki** [comment]
That makes a lot of sense, thank you. Out of curiosity, can there be multiple ROI per file? My label files have integer values corresponding to the ROI- do I need to separate them out into different ROI files with binary values?

**Comment by Hierakonpolis** [comment]
You need to separate them, it's very easy to automate if you need, in python you can just open them with nibabel, select the ROI with volume == value, and save that as a new file with the name of the roi.

**Comment by js-kki** [comment]
sounds good, thanks!

**Comment by js-kki** [comment]
<img width="1218" height="817" alt="Image" src="https://github.com/user-attachments/assets/df73af8d-3494-4220-a686-b97d3cf0b4f0" />

any idea what is causing this error? I'm using 2D labels, a 2D mask and 3D volumes

**Comment by Hierakonpolis** [comment]
I don't get it, why would you be doing that?
This is very straightforward. It trains a neural network and uses it for inference. It expects MRI volumes and expects masks in the same space as those volumes. It also generates masks in the same space as the input volumes. It doesn't do other things. It doesn't extrapolate from a 2D image to 3D, or adapt to any random way to organize your data. It just does one thing and it's a straightforward supervised learning task. You have been at this for one year and your questions are all about doing anything other than what it says on the label.

It only does what it says on the label.
Also, please consider using copy and paste for text.
